window.WaykaData = {
  clinic: 'Veterinaria San Roque',
  user: { name: 'Ana Rossi', role: 'Veterinaria' },
  patients: [
    { id:'p1', name:'Mora', species:'canino', breed:'Mestizo', sex:'Hembra', age:'4 años', weight:'8,4 kg', chip:'982 000 123 456 789',
      owner:'Julia Fernández', ownerPhone:'+54 9 11 5555-2020', lastVisit:'12 mar 2026',
      allergies:[{label:'Penicilina',severity:'alta'},{label:'Polen',severity:'baja'}],
      meds:[
        {name:'Meloxicam', dose:'0,1 mg/kg', frequency:'cada 24 h', until:'28 ago', prescriber:'Dra. A. Rossi', status:'activo'},
        {name:'Amoxicilina', dose:'15 mg/kg', frequency:'cada 12 h', until:'24 ago', prescriber:'Dr. M. Paz', status:'activo'},
        {name:'Ranitidina', dose:'2 mg/kg', frequency:'cada 12 h', prescriber:'Dra. A. Rossi', status:'finalizado'},
      ],
      events:[
        {kind:'consulta', title:'Control post-quirúrgico', date:'12 mar 2026', author:'Dra. A. Rossi', text:'Cicatriz limpia, sin secreción. Retiro de puntos en 5 días.', attachments:2},
        {kind:'cirugia', title:'Ovariohisterectomía', date:'28 feb 2026', author:'Dr. M. Paz', text:'Procedimiento sin complicaciones. Anestesia: propofol / isoflurano.', attachments:1},
        {kind:'estudio', title:'Hemograma completo', date:'26 feb 2026', author:'Lab. externo', text:'Valores dentro de rango. Leve leucocitosis.', attachments:1},
        {kind:'vacuna', title:'Vacuna quíntuple', date:'14 ene 2026', author:'Dra. A. Rossi', text:'Refuerzo anual. Sin reacción adversa.', attachments:0},
        {kind:'peso', title:'Registro de peso · 8,4 kg', date:'14 ene 2026', author:'Julia Fernández (tutora)', text:'', attachments:0},
      ] },
    { id:'p2', name:'Kira', species:'felino', breed:'Siamés', sex:'Hembra', age:'2 años', weight:'3,9 kg', chip:'982 000 987 654 321',
      owner:'Marcos Duarte', ownerPhone:'+54 9 11 4444-1010', lastVisit:'02 abr 2026', allergies:[], meds:[], events:[] },
    { id:'p3', name:'Tobi', species:'canino', breed:'Beagle', sex:'Macho', age:'7 años', weight:'14,2 kg', chip:'982 000 555 111 222',
      owner:'Lucía Ferrari', ownerPhone:'+54 9 11 3333-7788', lastVisit:'21 feb 2026',
      allergies:[{label:'Ibuprofeno',severity:'alta'}],
      meds:[{name:'Enalapril', dose:'0,5 mg/kg', frequency:'cada 24 h', prescriber:'Dra. A. Rossi', status:'activo'}], events:[] },
    { id:'p4', name:'Nube', species:'felino', breed:'Común europeo', sex:'Hembra', age:'11 años', weight:'4,6 kg', chip:'982 000 777 333 111',
      owner:'Pablo Sosa', ownerPhone:'+54 9 11 2222-9090', lastVisit:'30 mar 2026', allergies:[], meds:[], events:[] },
    { id:'p5', name:'Rocco', species:'canino', breed:'Bulldog francés', sex:'Macho', age:'3 años', weight:'11,8 kg', chip:'982 000 444 222 888',
      owner:'Sofía Blanco', ownerPhone:'+54 9 11 6666-4545', lastVisit:'08 abr 2026', allergies:[], meds:[], events:[] },
  ],
  agenda: [
    { time:'08:30', title:'Vacunación anual', patient:'Rocco', vet:'Dra. A. Rossi', status:'cumplido' },
    { time:'09:30', title:'Control post-quirúrgico', patient:'Mora', vet:'Dra. A. Rossi', status:'vencido' },
    { time:'10:15', title:'Consulta dermatológica', patient:'Tobi', vet:'Dr. M. Paz', status:'pendiente' },
    { time:'11:00', title:'Extracción de sangre', patient:'Nube', vet:'Dra. A. Rossi', status:'pendiente' },
    { time:'12:30', title:'Control de peso', patient:'Kira', vet:'Dr. M. Paz', status:'pendiente' },
  ],
  staff: [
    { name:'Ana Rossi', role:'Veterinaria', email:'a.rossi@sanroque.vet', matricula:'MP 4821', active:true },
    { name:'Martín Paz', role:'Veterinario', email:'m.paz@sanroque.vet', matricula:'MP 5104', active:true },
    { name:'Carla Ruiz', role:'Clínica admin', email:'c.ruiz@sanroque.vet', matricula:'—', active:true },
    { name:'Diego Lauro', role:'Veterinario', email:'d.lauro@sanroque.vet', matricula:'MP 3390', active:false },
  ],
};
