/**
 * ARCHIVO GENERADO — no editar a mano.
 * Fuente: design-system v1.5.0 (2026-08-28).
 * Regenerar: npm run tokens:generar
 *
 * Espejo en JS/TS de las custom properties de `/design-system/tokens/*.css`,
 * necesario porque en iOS/Android no existe el CSS. Los nombres son los mismos
 * del design system, a propósito: un token de acá se puede buscar tal cual en
 * los archivos entregados.
 *
 * No incluye los tokens que no son escalares (`--text-*` compuestos,
 * `--shadow-*`, `--ring-*`, `--transition-control`) — ver `sombras.ts` y
 * doc 09, sección 3.2.
 */

export const VERSION_DESIGN_SYSTEM = '1.5.0';

/** Tema default: clínica y veterinario (lila primario, naranjas de acento). */
export const tokensDefault = {
  '--alert-allergy-border': '#EDC7C1',
  '--alert-allergy-surface': '#FBEEEC',
  '--alert-allergy-text': '#8F3229',
  '--alert-medication-border': '#DFDBE5',
  '--alert-medication-surface': '#F6F4F8',
  '--alert-medication-text': '#493B6B',
  '--appt-done': '#31795A',
  '--appt-done-surface': '#EAF3EE',
  '--appt-overdue': '#B04438',
  '--appt-overdue-surface': '#FBEEEC',
  '--appt-pending': '#493B6B',
  '--appt-pending-surface': '#EBE6F4',
  '--border-brand': '#B4A3D6',
  '--border-danger': '#B04438',
  '--border-default': '#DFDBE5',
  '--border-focus': '#493B6B',
  '--border-on-immersive': 'rgba(255,255,255,.10)',
  '--border-on-nav': 'rgba(255,255,255,.10)',
  '--border-strong': '#C6C0CE',
  '--border-subtle': '#EDEAF1',
  '--clinical-accent': '#493B6B',
  '--clinical-border': '#DFDBE5',
  '--clinical-surface': '#F6F4F8',
  '--color-accent': '#F6A56C',
  '--color-accent-hover': '#D97B47',
  '--color-accent-soft': '#F9EEE4',
  '--color-accent-strong': '#B85F2E',
  '--color-primary': '#B4A3D6',
  '--color-primary-fg': '#FFFFFF',
  '--color-primary-fill': '#493B6B',
  '--color-primary-fill-fg': '#FFFFFF',
  '--color-primary-fill-hover': '#332850',
  '--color-primary-hover': '#897AAC',
  '--color-primary-soft': '#EBE6F4',
  '--color-primary-strong': '#493B6B',
  '--content-max': '1160px',
  '--control-h-lg': '48px',
  '--control-h-md': '40px',
  '--control-h-sm': '32px',
  '--control-h-touch': '52px',
  '--danger-100': '#F4D8D4',
  '--danger-50': '#FBEEEC',
  '--danger-500': '#B04438',
  '--danger-600': '#8F3229',
  '--ds-released': '"2026-08-27"',
  '--ds-version': '"1.5.0"',
  '--dur-fast': '140ms',
  '--dur-instant': '80ms',
  '--dur-normal': '220ms',
  '--dur-slow': '340ms',
  '--ease-in': 'cubic-bezier(.6,0,.9,.4)',
  '--ease-out': 'cubic-bezier(.16,1,.3,1)',
  '--ease-standard': 'cubic-bezier(.2,.7,.3,1)',
  '--font-display':
    '"Satoshi","Satoshi Static",-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif',
  '--font-mono': 'ui-monospace,"SF Mono",Menlo,Consolas,monospace',
  '--font-sans':
    '"Satoshi","Satoshi Static",-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif',
  '--fs-body': '15px',
  '--fs-body-lg': '17px',
  '--fs-body-sm': '13px',
  '--fs-caption': '12px',
  '--fs-display-lg': '44px',
  '--fs-display-md': '36px',
  '--fs-display-xl': '56px',
  '--fs-h1': '30px',
  '--fs-h2': '24px',
  '--fs-h3': '20px',
  '--fs-h4': '17px',
  '--fs-overline': '11px',
  '--fw-black': '900',
  '--fw-bold': '700',
  '--fw-light': '300',
  '--fw-medium': '500',
  '--fw-regular': '400',
  '--fw-semibold': '600',
  '--gutter-card': '24px',
  '--gutter-mobile': '20px',
  '--gutter-page': '32px',
  '--gutter-section': '40px',
  '--immersive-accent': '#B4A3D6',
  '--info-100': '#D5E0EE',
  '--info-50': '#EBF0F7',
  '--info-500': '#4A6FA5',
  '--info-600': '#38557F',
  '--lh-normal': '1.45',
  '--lh-relaxed': '1.6',
  '--lh-snug': '1.25',
  '--lh-tight': '1.1',
  '--logo-on-nav-filter': 'brightness(0) invert(1)',
  '--ls-body': '0',
  '--ls-display': '-0.02em',
  '--ls-heading': '-0.01em',
  '--ls-overline': '0.08em',
  '--nav-accent': '#B4A3D6',
  '--nav-accent-fg': '#201A2B',
  '--neutral-0': '#FFFFFF',
  '--neutral-100': '#EDEAF1',
  '--neutral-200': '#DFDBE5',
  '--neutral-25': '#FBFAFC',
  '--neutral-300': '#C6C0CE',
  '--neutral-400': '#A099AA',
  '--neutral-50': '#F6F4F8',
  '--neutral-500': '#7B7386',
  '--neutral-600': '#5D5568',
  '--neutral-700': '#443D4E',
  '--neutral-800': '#2C2635',
  '--neutral-900': '#201A2B',
  '--owner-accent': '#B85F2E',
  '--owner-border': '#EFDCC9',
  '--owner-surface': '#F9EEE4',
  '--radius-card': '16px',
  '--radius-control': '10px',
  '--radius-lg': '16px',
  '--radius-md': '12px',
  '--radius-pill': '999px',
  '--radius-sm': '8px',
  '--radius-xl': '22px',
  '--radius-xs': '4px',
  '--sidebar-w': '248px',
  '--space-0': '0px',
  '--space-1': '2px',
  '--space-10': '48px',
  '--space-11': '64px',
  '--space-12': '80px',
  '--space-13': '104px',
  '--space-2': '4px',
  '--space-3': '8px',
  '--space-4': '12px',
  '--space-5': '16px',
  '--space-6': '20px',
  '--space-7': '24px',
  '--space-8': '32px',
  '--space-9': '40px',
  '--success-100': '#CFE5D9',
  '--success-50': '#EAF3EE',
  '--success-500': '#31795A',
  '--success-600': '#245C43',
  '--surface-accent-soft': '#EBE6F4',
  '--surface-brand': '#B4A3D6',
  '--surface-brand-soft': '#EBE6F4',
  '--surface-card': '#FFFFFF',
  '--surface-disabled': '#EDEAF1',
  '--surface-hover': '#F6F4F8',
  '--surface-immersive': '#201A2B',
  '--surface-immersive-item': 'rgba(255,255,255,.10)',
  '--surface-immersive-item-hover': 'rgba(255,255,255,.06)',
  '--surface-inverse': '#332850',
  '--surface-nav': '#332850',
  '--surface-nav-deep': '#201A2B',
  '--surface-nav-item': 'rgba(255,255,255,.10)',
  '--surface-nav-item-hover': 'rgba(255,255,255,.06)',
  '--surface-page': '#FBFAFC',
  '--surface-raised': '#FFFFFF',
  '--surface-selected': '#EBE6F4',
  '--surface-sunken': '#F6F4F8',
  '--text-accent': '#493B6B',
  '--text-body': '#2C2635',
  '--text-brand': '#493B6B',
  '--text-danger': '#8F3229',
  '--text-inverse': '#FFFFFF',
  '--text-link': '#493B6B',
  '--text-link-hover': '#332850',
  '--text-muted': '#5D5568',
  '--text-on-immersive': '#FFFFFF',
  '--text-on-immersive-muted': 'rgba(255,255,255,.62)',
  '--text-on-nav': '#FFFFFF',
  '--text-on-nav-muted': 'rgba(255,255,255,.62)',
  '--text-strong': '#201A2B',
  '--text-subtle': '#7B7386',
  '--text-success': '#245C43',
  '--text-warning': '#855C13',
  '--warning-100': '#F2E3C2',
  '--warning-50': '#FAF3E4',
  '--warning-500': '#A9761F',
  '--warning-600': '#855C13',
  '--wayka-blanco': '#FFFFFF',
  '--wayka-lila': '#B4A3D6',
  '--wayka-lila-claro': '#EBE6F4',
  '--wayka-naranja': '#D97B47',
  '--wayka-naranja-claro': '#F6A56C',
  '--wayka-naranja-oscuro': '#B85F2E',
  '--wayka-oscuro': '#201A2B',
  '--wayka-violeta': '#493B6B',
  '--wayka-violeta-oscuro': '#332850',
} as const;

/**
 * Tema tutor: naranja primario, lilas de acento. Solo los tokens que redefine —
 * el resto se hereda del default vía merge en el ThemeProvider.
 */
export const tokensTutor = {
  '--alert-medication-text': '#B85F2E',
  '--appt-pending': '#B85F2E',
  '--appt-pending-surface': '#FDEEE1',
  '--border-brand': '#F6A56C',
  '--border-focus': '#B85F2E',
  '--border-on-nav': 'rgba(255,255,255,.26)',
  '--color-accent': '#B4A3D6',
  '--color-accent-hover': '#493B6B',
  '--color-accent-soft': '#EBE6F4',
  '--color-accent-strong': '#493B6B',
  '--color-primary': '#F6A56C',
  '--color-primary-fill': '#F6A56C',
  '--color-primary-fill-hover': '#EE9757',
  '--color-primary-hover': '#EE9757',
  '--color-primary-soft': '#FDEEE1',
  '--color-primary-strong': '#B85F2E',
  '--immersive-accent': '#F6A56C',
  '--nav-accent': '#493B6B',
  '--nav-accent-fg': '#FFFFFF',
  '--surface-accent-soft': '#FDEEE1',
  '--surface-brand': '#F6A56C',
  '--surface-brand-soft': '#FDEEE1',
  '--surface-nav': '#F6A56C',
  '--surface-nav-deep': '#EE9757',
  '--surface-nav-item': 'rgba(255,255,255,.20)',
  '--surface-nav-item-hover': 'rgba(255,255,255,.13)',
  '--surface-selected': '#FDEEE1',
  '--text-accent': '#B85F2E',
  '--text-brand': '#B85F2E',
  '--text-link': '#B85F2E',
  '--text-link-hover': '#EE9757',
  '--text-on-nav-muted': 'rgba(255,255,255,.86)',
} as const;

/**
 * Segundo juego de duraciones, declarado bajo `@media (prefers-reduced-motion)`.
 * En nativo se selecciona con `AccessibilityInfo.isReduceMotionEnabled()`.
 */
export const tokensReducedMotion = {
  '--dur-fast': '0ms',
  '--dur-normal': '0ms',
  '--dur-slow': '0ms',
} as const;

export type NombreToken = keyof typeof tokensDefault;
export type Tokens = Record<NombreToken, string>;
